version: "3"
services:
  db:
    image: 'postgres:latest'
    container_name: db
    restart: always
    environment:
        - POSTGRES_DB=ifood_db
        - POSTGRES_USER=ifoodUser
        - POSTGRES_PASSWORD=ifoodPassword
        - PGDATA=/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
        - 5432:5432
    expose:
        - 5432
    volumes:
        - pgdata:/var/lib/postgresql/data
        - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql
        - ./data/criar-tabela.sql:/docker-entrypoint-initdb.d/criar-tabela.sql

volumes:
  pgdata:
